import { useEffect } from 'react';
import { LegalPageLayout, LegalSection, type LegalSectionDefinition } from '@/components/legal/LegalPageLayout';
import { setMetaTags } from '@/lib/seo';

export const PRIVACY_SECTIONS = [
  { id: 'introduction', title: 'Introduction' }, { id: 'information-we-collect', title: 'Information We Collect' }, { id: 'how-we-use-your-information', title: 'How We Use Your Information' }, { id: 'ai-processing', title: 'AI Processing' }, { id: 'sharing-your-information', title: 'Sharing Your Information' }, { id: 'cookies-and-tracking', title: 'Cookies & Tracking' }, { id: 'data-security', title: 'Data Security' }, { id: 'data-retention', title: 'Data Retention' }, { id: 'your-rights', title: 'Your Rights' }, { id: 'childrens-privacy', title: "Children's Privacy" }, { id: 'international-transfers', title: 'International Transfers' }, { id: 'changes-to-this-policy', title: 'Changes to This Policy' }, { id: 'contact', title: 'Contact' },
] as const satisfies readonly LegalSectionDefinition[];

export default function PrivacyPolicy() {
  useEffect(() => { setMetaTags({ title: 'Privacy Policy — Syncareer', description: 'How Syncareer collects, uses and handles information.', ogTitle: 'Syncareer Privacy Policy', ogDescription: 'How Syncareer collects, uses and handles information.', ogUrl: 'https://syncareer.me/privacy', canonical: 'https://syncareer.me/privacy' }); }, []);
  return <LegalPageLayout document="privacy" eyebrow="PRIVACY" title="Privacy Policy" description="How Syncareer collects, uses and handles information." effectiveDate="1 February 2026" sections={PRIVACY_SECTIONS}>
    <LegalSection number={1} {...PRIVACY_SECTIONS[0]}><p>Syncareer ("we", "us", "our") respects your privacy. This Privacy Policy explains how we collect, use, store, and protect your personal information when you use the Syncareer platform, website, and services (the "Service").</p></LegalSection>
    <LegalSection number={2} {...PRIVACY_SECTIONS[1]}><p>We collect information you provide directly, including:</p><ul><li>Account information: name, email, password, role (student, counsellor, employer)</li><li>Profile information: education, skills, work history, career preferences, profile photo</li><li>Generated content: CVs, assessment responses, interview recordings, portfolio uploads</li><li>Payment information: processed securely by Paystack — we do not store full card details</li><li>Communication: messages with counsellors, support requests, feedback</li></ul><p>We also automatically collect: device type, browser, IP address, pages visited, and approximate location (for language detection).</p></LegalSection>
    <LegalSection number={3} {...PRIVACY_SECTIONS[2]}><ul><li>Provide and personalize career recommendations and AI insights</li><li>Match students with counsellors and employers</li><li>Process payments and manage subscriptions</li><li>Send transactional emails (account, security, session reminders)</li><li>Send product updates and marketing emails (only with your consent — you can opt out anytime)</li><li>Improve the Service through analytics and aggregated research</li><li>Detect fraud, abuse, and security incidents</li></ul></LegalSection>
    <LegalSection number={4} {...PRIVACY_SECTIONS[3]}><p>Your assessment answers, CV content, and interview responses are processed by AI models (Google Gemini, OpenAI GPT) via the Lovable AI Gateway to generate recommendations. This data is sent for inference only and is not used to train third-party models.</p></LegalSection>
    <LegalSection number={5} {...PRIVACY_SECTIONS[4]}><p>We do not sell your personal data. We share information only with:</p><ul><li>Service providers: Supabase (database/auth), Paystack (payments), Resend (email), Lovable AI Gateway (AI inference)</li><li>Counsellors you book sessions with — they see only the information needed to support you</li><li>Employers — only if you explicitly apply to a job posting or make your portfolio public</li><li>Legal authorities — when required by law or to protect rights and safety</li></ul></LegalSection>
    <LegalSection number={6} {...PRIVACY_SECTIONS[5]}><p>We use essential cookies for authentication and session management, and analytics cookies (where consented) to improve the Service. You can control cookies through your browser settings. Disabling essential cookies may break sign-in.</p></LegalSection>
    <LegalSection number={7} {...PRIVACY_SECTIONS[6]}><p>We use industry-standard measures: HTTPS, encrypted storage, Row-Level Security on the database, hashed passwords, optional two-factor authentication. No system is 100% secure — please use a strong, unique password.</p></LegalSection>
    <LegalSection number={8} {...PRIVACY_SECTIONS[7]}><p>We keep your data for as long as your account is active. If you delete your account, we permanently remove your personal data within 30 days, except where retention is required by law (e.g., financial records).</p></LegalSection>
    <LegalSection number={9} {...PRIVACY_SECTIONS[8]}><p>You have the right to:</p><ul><li>Access, correct, or download your personal data</li><li>Delete your account and associated data</li><li>Withdraw consent for marketing emails at any time</li><li>Object to certain processing activities</li></ul><p>To exercise these rights, email <a href="mailto:syncareer01@gmail.com">syncareer01@gmail.com</a>.</p></LegalSection>
    <LegalSection number={10} {...PRIVACY_SECTIONS[9]}><p>Syncareer is intended for users aged 16 and older. We do not knowingly collect data from children under 16. If we learn we have, we will delete it.</p></LegalSection>
    <LegalSection number={11} {...PRIVACY_SECTIONS[10]}><p>Your data may be processed in countries other than your own (e.g., the United States, European Union) by our service providers. We ensure appropriate safeguards are in place.</p></LegalSection>
    <LegalSection number={12} {...PRIVACY_SECTIONS[11]}><p>We may update this Policy. Material changes will be communicated via email or in-app notice. Continued use after updates constitutes acceptance.</p></LegalSection>
    <LegalSection number={13} {...PRIVACY_SECTIONS[12]}><ul><li>Email: <a href="mailto:syncareer01@gmail.com">syncareer01@gmail.com</a></li><li>Website: <a href="https://syncareer.me">https://syncareer.me</a></li></ul></LegalSection>
  </LegalPageLayout>;
}
