import type { ReactNode } from 'react';
import { Minus, TrendingDown, TrendingUp, Info } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils';
import type { MarketIntelligence } from '@/hooks/useMarketIntelligence';
import { formatReportDate, REGION_LABELS } from '@/features/market-intelligence/derive';

/**
 * Shared presentation pieces for Market Intelligence. These carry the
 * provenance/estimate language so no section can present an AI figure as a
 * verified statistic.
 */

export function MarketSection({
  id,
  eyebrow,
  title,
  description,
  children,
  className,
}: {
  id: string;
  eyebrow: string;
  title: string;
  description?: string;
  children: ReactNode;
  className?: string;
}) {
  return (
    <section
      aria-labelledby={`${id}-title`}
      className={cn('surface-content rounded-surface-lg p-5 sm:p-6', className)}
    >
      <p className="type-label text-primary">{eyebrow}</p>
      <h2 id={`${id}-title`} className="type-section-title mt-1">
        {title}
      </h2>
      {description && <p className="type-secondary mt-1 max-w-3xl">{description}</p>}
      <div className="mt-4">{children}</div>
    </section>
  );
}

export function TrendBadge({ trend, className }: { trend: string; className?: string }) {
  const Icon = trend === 'rising' ? TrendingUp : trend === 'declining' ? TrendingDown : Minus;
  const iconClass =
    trend === 'rising'
      ? 'text-success'
      : trend === 'declining'
        ? 'text-destructive'
        : 'text-muted-foreground';
  return (
    <Badge variant="soft-neutral" className={cn('gap-1', className)}>
      <Icon aria-hidden="true" className={cn('size-3', iconClass)} />
      {trend === 'rising' ? 'Rising' : trend === 'declining' ? 'Declining' : 'Stable'}
    </Badge>
  );
}

/** Inline marker that a figure is a model estimate, not verified data. */
export function EstimateChip({ className }: { className?: string }) {
  return (
    <Badge variant="soft-neutral" className={cn('gap-1', className)}>
      <Info aria-hidden="true" className="size-3" />
      AI estimate
    </Badge>
  );
}

type ConfidenceLevel = 'high' | 'medium' | 'low';
const CONFIDENCE_COPY: Record<
  ConfidenceLevel,
  { label: string; variant: 'soft-success' | 'soft-primary' | 'soft-warning' }
> = {
  high: { label: 'Higher confidence', variant: 'soft-success' },
  medium: { label: 'Medium confidence', variant: 'soft-primary' },
  low: { label: 'Lower confidence', variant: 'soft-warning' },
};

/**
 * Provenance and freshness: the honest context every figure on the page rests
 * on. Rendered once near the top so the whole report is read in context.
 */
export function ProvenanceNote({
  data,
  major,
  className,
}: {
  data: MarketIntelligence;
  major: string;
  className?: string;
}) {
  const level: ConfidenceLevel =
    data.data_confidence === 'high' || data.data_confidence === 'low'
      ? data.data_confidence
      : 'medium';
  const confidence = CONFIDENCE_COPY[level];
  const regionLabel = REGION_LABELS[data.region] ?? data.region;

  return (
    <div
      className={cn(
        'rounded-surface border border-border-subtle bg-surface-secondary/60 p-4',
        className,
      )}
    >
      <div className="flex items-start gap-2.5">
        <Info aria-hidden="true" className="mt-0.5 size-4 shrink-0 text-muted-foreground" />
        <div className="min-w-0 space-y-1.5">
          <p className="text-xs leading-5 text-foreground-secondary">
            <span className="font-semibold text-foreground">How this is produced.</span> These
            figures are estimates generated by an AI model from general labour-market knowledge of{' '}
            {major} in {regionLabel}. They are not live job-posting counts, government statistics or
            verified salary data — treat direction and relative ranking as informative, and exact
            numbers as uncertain.
          </p>
          <div className="flex flex-wrap items-center gap-x-4 gap-y-1.5">
            <Badge variant={confidence.variant} className="gap-1">
              {confidence.label}
            </Badge>
            <span className="type-meta">
              Generated {formatReportDate(data.generated_at)}
              {data.from_cache ? ' · served from 7-day cache' : ' · just generated'}
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
