kind = "mobile"
previewPath = "/syncareer-mobile/"
title = "Syncareer Mobile"
version = "1.0.0"
id = "artifacts/syncareer-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/syncareer-mobile/" ]
localPort = 24565

[services.development]
run = "pnpm --filter @workspace/syncareer-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/syncareer-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/syncareer-mobile", "run", "serve" ]

[services.env]
PORT = "24565"
BASE_PATH = "/syncareer-mobile/"
